#line 2 "wordcount.c"

#line 4 "wordcount.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 62
#define YY_END_OF_BUFFER 63
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[203] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,   63,   61,
        1,    2,   61,   31,   48,   24,   28,   61,   32,   33,
       23,   38,   23,   61,   24,   19,   39,   27,   29,   27,
       21,   21,   36,   37,   28,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   34,   28,   35,   54,   53,
       54,   49,   54,   41,   43,   41,   41,   45,   46,   45,
       45,    1,    2,   27,   30,   60,    0,   59,   60,   25,
       26,   55,    0,   44,   40,    0,   19,   58,   58,   28,
       21,    0,   56,   21,   21,   21,   21,   21,   21,    4,
       21,   21,   21,    6,   21,   21,   21,   21,   21,   53,

       52,    0,   50,   51,   43,   42,    0,   46,   47,    0,
       22,    0,    0,   55,    0,   20,   58,   58,    0,   20,
        0,   56,   21,   21,   21,   21,   21,   21,   21,   21,
        3,   16,   21,   21,   21,   21,   57,   60,   22,    0,
       55,   20,   58,   20,   20,   21,    9,   15,   21,   21,
       21,    7,   21,   21,   21,   14,   21,   55,    0,   20,
       20,   56,   58,   10,   21,   21,   21,   17,   21,   21,
        5,   55,   20,   20,   58,   56,    0,   58,   21,   21,
       18,   13,    8,   55,   58,   20,    0,   56,    0,   58,
       21,   11,    0,   55,    0,    0,   12,   55,   55,    0,

       55,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   19,   19,    1,   20,   21,
       22,   23,    1,    1,   24,   24,   24,   24,   25,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       26,   27,   28,   29,   24,    1,   30,   31,   32,   33,

       34,   35,   24,   36,   37,   24,   38,   39,   24,   40,
       41,   24,   24,   42,   43,   44,   45,   46,   47,   24,
       24,   24,   48,   49,   50,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[51] =
    {   0,
        1,    1,    2,    3,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    4,    1,    5,    5,    1,
        1,    1,    1,    5,    5,    1,    1,    1,    1,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    1,    1,    1
    } ;

static const flex_int16_t yy_base[212] =
    {   0,
        0,    0,   48,   52,   56,   58,   60,   62,  388,  389,
      385,  389,  383,  363,  389,  389,  376,   64,  389,  389,
      370,  389,  367,   51,   59,   62,  389,   67,  359,   70,
        0,   82,  389,  389,  389,  338,   69,   43,  340,   63,
       68,  344,  330,  335,  339,  389,  325,  389,  389,  389,
      370,  389,  108,  389,  389,  369,  103,  389,  389,  368,
      353,  367,  389,  389,  389,  359,  358,  357,  146,  389,
      389,   97,  102,  389,  389,  109,  126,  105,  143,  389,
        0,  114,  118,  134,  331,  321,  333,  322,  324,  313,
      311,  312,  304,    0,  283,  279,  282,  278,  274,  389,

      389,  304,  389,  389,  389,  389,  296,  389,  389,  286,
      389,  277,  272,  149,  174,  166,  122,  151,  178,  183,
      187,  191,  249,  243,  232,  226,  235,  232,  200,  200,
        0,    0,  181,  179,  186,  169,  389,  389,  389,  153,
      160,  188,  198,  196,  202,  160,    0,    0,  158,  135,
      136,    0,  122,  121,  125,    0,  119,  206,  210,  214,
      219,  223,  230,    0,  106,   90,   85,    0,   69,   58,
        0,  232,  236,  240,  249,  253,  228,  242,   45,   42,
        0,    0,    0,  257,  265,  269,  271,  274,  278,  282,
       48,    0,  284,  286,  290,  294,    0,  298,  302,  306,

      310,  389,  329,  334,  339,  344,  346,   52,  351,   48,
      356
    } ;

static const flex_int16_t yy_def[212] =
    {   0,
      202,    1,  203,  203,  204,  204,  205,  205,  202,  202,
      202,  202,  202,  202,  202,  202,  202,  206,  202,  202,
      202,  202,  202,  202,  202,  207,  202,  202,  202,  202,
      208,  208,  202,  202,  202,  208,  208,  208,   32,  208,
      208,  208,  208,  208,  208,  202,  202,  202,  202,  202,
      202,  202,  202,  202,  202,  202,  202,  202,  202,  202,
      202,  202,  202,  202,  202,  209,  209,  209,  209,  202,
      202,  202,  202,  202,  202,  202,  207,  210,  210,  202,
      208,  202,  202,   32,  208,  208,  208,  208,  208,  208,
      208,  208,  208,  208,  208,  208,  208,  208,  208,  202,

      202,  202,  202,  202,  202,  202,  202,  202,  202,  209,
      202,  211,  209,  202,  202,  207,  210,  210,  202,  210,
      202,  202,  208,  208,  208,  208,  208,  208,  208,  208,
      208,  208,  208,  208,  208,  208,  202,  202,  202,  202,
      202,  116,  210,  207,  210,  208,  208,  208,  208,  208,
      208,  208,  208,  208,  208,  208,  208,  202,  202,  210,
      207,  202,  210,  208,  208,  208,  208,  208,  208,  208,
      208,  116,  207,  145,  210,  161,  202,  210,  208,  208,
      208,  208,  208,  161,  210,  161,  202,  161,  207,  145,
      208,  208,  202,  210,  161,  161,  208,  207,  145,  161,

      161,    0,  202,  202,  202,  202,  202,  202,  202,  202,
      202
    } ;

static const flex_int16_t yy_nxt[440] =
    {   0,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   16,   21,   22,   23,   24,   25,   26,   26,   27,
       28,   29,   30,   31,   32,   33,   10,   34,   35,   31,
       36,   37,   38,   39,   40,   31,   41,   31,   31,   31,
       31,   42,   43,   31,   31,   44,   45,   46,   47,   48,
       50,   51,  118,   52,   50,   51,   81,   52,   55,   56,
       55,   56,   59,   60,   59,   60,   72,   67,   73,   73,
       74,   61,   68,   61,   53,   75,   89,   76,   53,   77,
       77,  197,   57,   90,   57,  192,   79,   80,   64,  191,
       69,   64,   80,  183,   82,   79,   82,   83,   86,   84,

       84,   92,   94,   93,   87,  106,  107,   95,  182,   88,
      101,  102,   72,  103,  114,  114,  104,   72,  181,   73,
       73,  115,  117,  117,   72,  104,  116,  116,  180,   83,
      115,  121,  121,   83,  104,  122,  122,  104,  104,  117,
      117,   76,  104,   77,   77,  179,  202,  104,  202,  104,
       79,  104,  171,  104,  112,  119,  170,  119,   83,   79,
      120,  120,  169,  113,   72,  168,  114,  114,  117,  117,
      141,  141,  113,  115,  167,  113,  113,  141,  141,  166,
      113,   72,  115,  142,  142,  113,  140,  113,  140,  113,
      143,  141,  141,   83,  165,  144,  144,  164,   83,  143,

      145,  145,   83,  158,  121,  121,   83,  157,  122,  122,
      159,   83,  159,  161,  161,  160,  160,  162,  156,  145,
      145,   72,  155,  172,  172,  154,  163,  173,  173,  153,
      115,  174,  174,  152,  162,  163,  161,  161,   83,  115,
      176,  176,  177,  175,  177,  189,  189,  178,  178,  184,
      184,  202,  175,  186,  186,  187,  185,  174,  174,  190,
      190,  177,  151,  177,  150,  185,  178,  178,   83,  149,
      188,  188,  158,  148,  184,  184,  147,  193,  146,  193,
      139,  185,  194,  194,  187,  111,  186,  186,  195,  195,
      185,  188,  188,  202,  137,  196,  196,  187,  106,  190,

      190,  198,  198,  199,  199,  202,  101,  200,  200,  187,
      136,  196,  196,  202,  135,  201,  201,  187,  134,  199,
      199,  187,  133,  200,  200,  187,  132,  201,  201,   49,
       49,   49,   49,   49,   54,   54,   54,   54,   54,   58,
       58,   58,   58,   58,   66,  131,   66,   66,   66,   78,
       78,  110,  130,  129,  110,  110,  138,  128,  127,  138,
      138,  126,  125,  124,  123,  202,  202,  111,   62,  109,
      108,  105,  100,   65,   99,   98,   97,   96,   91,   85,
       64,   71,   70,   65,   64,   63,   62,  202,    9,  202,
      202,  202,  202,  202,  202,  202,  202,  202,  202,  202,

      202,  202,  202,  202,  202,  202,  202,  202,  202,  202,
      202,  202,  202,  202,  202,  202,  202,  202,  202,  202,
      202,  202,  202,  202,  202,  202,  202,  202,  202,  202,
      202,  202,  202,  202,  202,  202,  202,  202,  202
    } ;

static const flex_int16_t yy_chk[440] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    3,  210,    3,    4,    4,  208,    4,    5,    5,
        6,    6,    7,    7,    8,    8,   24,   18,   24,   24,
       25,    7,   18,    8,    3,   25,   38,   26,    4,   26,
       26,  191,    5,   38,    6,  180,   26,   28,   28,  179,
       18,   30,   30,  170,   32,   26,   32,   32,   37,   32,

       32,   40,   41,   40,   37,   57,   57,   41,  169,   37,
       53,   53,   72,   53,   72,   72,   53,   73,  167,   73,
       73,   72,   78,   78,   76,   53,   76,   76,  166,   82,
       72,   82,   82,   83,   53,   83,   83,   53,   53,  117,
      117,   77,   53,   77,   77,  165,   84,   53,   84,   53,
       77,   53,  157,   53,   69,   79,  155,   79,   79,   77,
       79,   79,  154,   69,  114,  153,  114,  114,  118,  118,
      140,  140,   69,  114,  151,   69,   69,  141,  141,  150,
       69,  116,  114,  116,  116,   69,  115,   69,  115,   69,
      116,  115,  115,  119,  149,  119,  119,  146,  120,  116,

      120,  120,  121,  142,  121,  121,  122,  136,  122,  122,
      143,  144,  143,  144,  144,  143,  143,  145,  135,  145,
      145,  158,  134,  158,  158,  133,  145,  159,  159,  130,
      158,  160,  160,  129,  161,  145,  161,  161,  162,  158,
      162,  162,  163,  161,  163,  177,  177,  163,  163,  172,
      172,  173,  161,  173,  173,  174,  172,  174,  174,  178,
      178,  175,  128,  175,  127,  172,  175,  175,  176,  126,
      176,  176,  184,  125,  184,  184,  124,  185,  123,  185,
      113,  184,  185,  185,  186,  112,  186,  186,  187,  187,
      184,  188,  188,  189,  110,  189,  189,  190,  107,  190,

      190,  193,  193,  194,  194,  195,  102,  195,  195,  196,
       99,  196,  196,  198,   98,  198,  198,  199,   97,  199,
      199,  200,   96,  200,  200,  201,   95,  201,  201,  203,
      203,  203,  203,  203,  204,  204,  204,  204,  204,  205,
      205,  205,  205,  205,  206,   93,  206,  206,  206,  207,
      207,  209,   92,   91,  209,  209,  211,   90,   89,  211,
      211,   88,   87,   86,   85,   68,   67,   66,   62,   61,
       60,   56,   51,   47,   45,   44,   43,   42,   39,   36,
       29,   23,   21,   17,   14,   13,   11,    9,  202,  202,
      202,  202,  202,  202,  202,  202,  202,  202,  202,  202,

      202,  202,  202,  202,  202,  202,  202,  202,  202,  202,
      202,  202,  202,  202,  202,  202,  202,  202,  202,  202,
      202,  202,  202,  202,  202,  202,  202,  202,  202,  202,
      202,  202,  202,  202,  202,  202,  202,  202,  202
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[63] =
    {   0,
0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 
    0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "1905028.l"



#line 10 "1905028.l"

#include<bits/stdc++.h>
#include "1905028_SymbolInfo.h"
#include "1905028_ScopeTable.h"
#include "1905028_SymbolTable.h"
// #include "y.tab.hpp"

using namespace std;

int line_count=1;
int lexeme_start_line=0; 
int errors=0;
string current_lexeme;
string str_token;
bool single_line_string=true;

ofstream logout;



// int bucket=10;
// Symbol_Table symbolTable(bucket);

string Uppercase(string temp)
{
	for(auto &t:temp)
	{t=toupper(t);}
	return temp;
}


char Lexeme_To_Char(const char* temp)
{	
	if(strlen(temp)==3)return temp[1];
	else if(temp[2]=='n')return '\n';
	else if(temp[2]=='a')return '\a';
	else if(temp[2]=='t')return '\t';
	else if(temp[2]=='\\')return '\\';
	else if(temp[2]=='r')return '\r';
	else if(temp[2]=='b')return '\b';
	else if(temp[2]=='0')return '\0';
	else if(temp[2]=='v')return '\v';
	else if(temp[2]=='\"')return '\"';
	else if(temp[2]=='f')return '\f';

	return '\a';
}

// FILE *logout;
// FILE *tokenout;



void Print_log(int l,string t, string lex)
{
	logout<<"Line# "<<l<<": Token <"<<t<<"> Lexeme "<<lex<<" found\n";
}


// void Print_token(string t,string l)
// {
// 	tokenout<<"<"<<t<<", "<<l<<">\n";
// }


void Print_error(int l, string s,string msg)
{
	// logout<<"Error at line# "<<l<<": "<<msg<<" "<<s<<"\n";
}

string ESC_IN_STRING(string temp)
{
	// cout<<"In escape processor\n";
	if(temp[1]=='n')return "\n";
	else if(temp[1]=='a')return "\a";
	else if(temp[1]=='t')return "\t";
	else if(temp[1]=='\\')return "\\";
	else if(temp[1]=='\'')return "\'";
	else if(temp[1]=='r')return "\r";
	else if(temp[1]=='b')return "\b";
	else if(temp[1]=='0')return "\0";
	else if(temp[1]=='v')return "\v";
	else if(temp[1]=='\"')return "\"";
	else if(temp[1]=='f')return "\f";

	return "z";	
}



#line 732 "wordcount.c"
#line 733 "wordcount.c"

#define INITIAL 0
#define STRING_STATE 1
#define SINGLE_LINE_COMMENT_STATE 2
#define MULTILINE_COMMENT_STATE 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 114 "1905028.l"

#line 955 "wordcount.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 203 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 389 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 115 "1905028.l"
{}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 116 "1905028.l"
{line_count++;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 118 "1905028.l"
{
	Print_log(line_count,Uppercase(yytext),yytext);
	TreeNode *tn=new TreeNode(new Symbol_Info(yytext,""+Uppercase(yytext)),Uppercase(yytext)+" : "+yytext+"\t"+"<Line : ");
	tn->first_line= tn->last_line=yylineno;
	tn->is_Terminal=true;
	tn->output_text+=(to_string(tn->first_line)+">");
	//yylval.TreeNode=tn;
	//return FOR;
	cout<<tn->output_text<<endl;
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 130 "1905028.l"
{
	Print_log(line_count,Uppercase(yytext),yytext);
	TreeNode *tn=new TreeNode(new Symbol_Info(yytext,""+Uppercase(yytext)),Uppercase(yytext)+" : "+yytext+"\t"+"<Line : ");
	tn->first_line= tn->last_line=yylineno;
	tn->is_Terminal=true;	
	tn->output_text+=(to_string(tn->first_line)+">");

	//yylval.TreeNode=tn;
	//return DO;
	cout<<tn->output_text<<endl;

}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 144 "1905028.l"
{
	Print_log(line_count,Uppercase(yytext),yytext);
	TreeNode *tn=new TreeNode(new Symbol_Info(yytext,""+Uppercase(yytext)),Uppercase(yytext)+" : "+yytext+"\t"+"<Line : ");
	tn->first_line= tn->last_line=yylineno;
	tn->is_Terminal=true;
	tn->output_text+=(to_string(tn->first_line)+">");
	//yylval.TreeNode=tn;
	//return WHILE;
	cout<<tn->output_text<<endl;

}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 156 "1905028.l"
{
	Print_log(line_count,Uppercase(yytext),yytext);
	TreeNode *tn=new TreeNode(new Symbol_Info(yytext,""+Uppercase(yytext)),Uppercase(yytext)+" : "+yytext+"\t"+"<Line : ");
	tn->first_line= tn->last_line=yylineno;
	tn->is_Terminal=true;
	tn->output_text+=(to_string(tn->first_line)+">");

	//yylval.TreeNode=tn;
	//return IF;
	cout<<tn->output_text<<endl;

}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 169 "1905028.l"
{
	Print_log(line_count,Uppercase(yytext),yytext);
	TreeNode *tn=new TreeNode(new Symbol_Info(yytext,""+Uppercase(yytext)),Uppercase(yytext)+" : "+yytext+"\t"+"<Line : ");
	tn->first_line= tn->last_line=yylineno;
	tn->is_Terminal=true;
	tn->output_text+=(to_string(tn->first_line)+">");

	//yylval.TreeNode=tn;
	//return ELSE;
	cout<<tn->output_text<<endl;

}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 182 "1905028.l"
{
	Print_log(line_count,Uppercase(yytext),yytext);
	TreeNode *tn=new TreeNode(new Symbol_Info(yytext,""+Uppercase(yytext)),Uppercase(yytext)+" : "+yytext+"\t"+"<Line : ");
	tn->first_line= tn->last_line=yylineno;
	tn->is_Terminal=true;
	tn->output_text+=(to_string(tn->first_line)+">");

	//yylval.TreeNode=tn;
	//return SWITCH;
	cout<<tn->output_text<<endl;

}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 195 "1905028.l"
{
	Print_log(line_count,Uppercase(yytext),yytext);
	TreeNode *tn=new TreeNode(new Symbol_Info(yytext,""+Uppercase(yytext)),Uppercase(yytext)+" : "+yytext+"\t"+"<Line : ");
	tn->first_line= tn->last_line=yylineno;
	tn->is_Terminal=true;		
	tn->output_text+=(to_string(tn->first_line)+">");

	//yylval.TreeNode=tn;
	//return CASE;
	cout<<tn->output_text<<endl;

}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 208 "1905028.l"
{
	Print_log(line_count,Uppercase(yytext),yytext);
	TreeNode *tn=new TreeNode(new Symbol_Info(yytext,""+Uppercase(yytext)),Uppercase(yytext)+" : "+yytext+"\t"+"<Line : ");
	tn->first_line= tn->last_line=yylineno;
	tn->is_Terminal=true;
	tn->output_text+=(to_string(tn->first_line)+">");
	//yylval.TreeNode=tn;
	//return BREAK;
	cout<<tn->output_text<<endl;

}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 221 "1905028.l"
{
	Print_log(line_count,Uppercase(yytext),yytext);
	TreeNode *tn=new TreeNode(new Symbol_Info(yytext,""+Uppercase(yytext)),Uppercase(yytext)+" : "+yytext+"\t"+"<Line : ");
	tn->first_line= tn->last_line=yylineno;
	tn->is_Terminal=true;
	tn->output_text+=(to_string(tn->first_line)+">");
	//yylval.TreeNode=tn;
	//return DEFAULT;
	cout<<tn->output_text<<endl;

}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 233 "1905028.l"
{
	Print_log(line_count,Uppercase(yytext),yytext);
	TreeNode *tn=new TreeNode(new Symbol_Info(yytext,""+Uppercase(yytext)),Uppercase(yytext)+" : "+yytext+"\t"+"<Line : ");
	tn->first_line= tn->last_line=yylineno;
	tn->is_Terminal=true;
	tn->output_text+=(to_string(tn->first_line)+">");
	//yylval.TreeNode=tn;
	//return CONTINUE;
	cout<<tn->output_text<<endl;

}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 245 "1905028.l"
{
	Print_log(line_count,Uppercase(yytext),yytext);
	TreeNode *tn=new TreeNode(new Symbol_Info(yytext,""+Uppercase(yytext)),Uppercase(yytext)+" : "+yytext+"\t"+"<Line : ");
	tn->first_line= tn->last_line=yylineno;
	tn->is_Terminal=true;
	tn->output_text+=(to_string(tn->first_line)+">");
	//yylval.TreeNode=tn;
	//return RETURN;
	cout<<tn->output_text<<endl;

}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 257 "1905028.l"
{
	Print_log(line_count,Uppercase(yytext),yytext);
	TreeNode *tn=new TreeNode(new Symbol_Info(yytext,""+Uppercase(yytext)),Uppercase(yytext)+" : "+yytext+"\t"+"<Line : ");
	tn->first_line= tn->last_line=yylineno;
	tn->is_Terminal=true;
	tn->output_text+=(to_string(tn->first_line)+">");
	//yylval.TreeNode=tn;
	//return VOID;
	cout<<tn->output_text<<endl;

}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 269 "1905028.l"
{
	Print_log(line_count,Uppercase(yytext),yytext);
	TreeNode *tn=new TreeNode(new Symbol_Info(yytext,""+Uppercase(yytext)),Uppercase(yytext)+" : "+yytext+"\t"+"<Line : ");
	tn->first_line= tn->last_line=yylineno;
	tn->is_Terminal=true;
	tn->output_text+=(to_string(tn->first_line)+">");
	//yylval.TreeNode=tn;
	//return CHAR;
	cout<<tn->output_text<<endl;

}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 281 "1905028.l"
{
	Print_log(line_count,Uppercase(yytext),yytext);
	TreeNode *tn=new TreeNode(new Symbol_Info(yytext,""+Uppercase(yytext)),Uppercase(yytext)+" : "+yytext+"\t"+"<Line : ");
	tn->first_line= tn->last_line=yylineno;
	tn->is_Terminal=true;
	tn->output_text+=(to_string(tn->first_line)+">");
	//yylval.TreeNode=tn;
	//return INT;
	cout<<tn->output_text<<endl;

}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 293 "1905028.l"
{
	Print_log(line_count,Uppercase(yytext),yytext);
	TreeNode *tn=new TreeNode(new Symbol_Info(yytext,""+Uppercase(yytext)),Uppercase(yytext)+" : "+yytext+"\t"+"<Line : ");
	tn->first_line= tn->last_line=yylineno;
	tn->is_Terminal=true;
	tn->output_text+=(to_string(tn->first_line)+">");
	//yylval.TreeNode=tn;
	//return FLOAT;
	cout<<tn->output_text<<endl;

}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 305 "1905028.l"
{
	Print_log(line_count,Uppercase(yytext),yytext);
	TreeNode *tn=new TreeNode(new Symbol_Info(yytext,""+Uppercase(yytext)),Uppercase(yytext)+" : "+yytext+"\t"+"<Line : ");
	tn->first_line= tn->last_line=yylineno;
	tn->is_Terminal=true;
	tn->output_text+=(to_string(tn->first_line)+">");
	//yylval.TreeNode=tn;
	//return DOUBLE;
	cout<<tn->output_text<<endl;

}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 318 "1905028.l"
{
	// Print_token("CONST_INT",yytext);
	Print_log(line_count,"CONST_INT",yytext);
	TreeNode *tn=new TreeNode(new Symbol_Info(yytext,"CONST_INT"),"CONST_INT : " + string(yytext)+"\t<Line : ");
	tn->first_line=tn->last_line=yylineno;
	tn->is_Terminal=true;
	tn->output_text+=(to_string(tn->first_line)+">");
	//yylval.TreeNode=tn;
	//return CONST_INT;
	cout<<tn->output_text<<endl;


}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 332 "1905028.l"
{
	// Print_token("CONST_FLOAT",yytext);
	Print_log(line_count,"CONST_FLOAT",yytext);
	TreeNode *tn=new TreeNode(new Symbol_Info(yytext,"CONST_FLOAT"),"CONST_FLOAT : "+ string(yytext)+"\t<Line : ");
	tn->first_line=tn->last_line=yylineno;
	tn->is_Terminal=true;
	tn->output_text+=(to_string(tn->first_line)+">");
	//yylval.TreeNode=tn;
	//return CONST_FLOAT;
	cout<<tn->output_text<<endl;

}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 345 "1905028.l"
{
	// Print_token("ID",yytext);
	Print_log(line_count,"ID",yytext);
	// if(symbolTable.Insert(yytext,"ID"))symbolTable.PrintAllScope();
	TreeNode *tn=new TreeNode(new Symbol_Info(yytext,"ID"),"ID : "+ string(yytext)+"\t<Line : ");
	tn->first_line=tn->last_line=yylineno;
	tn->is_Terminal=true;
	tn->output_text+=(to_string(tn->first_line)+">");
	//yylval.TreeNode=tn;
	//return ID;
	cout<<tn->output_text<<endl;



}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 361 "1905028.l"
{
	// Print_log(line_count,"CONST_CHAR",Lexeme_To_Char(yytext));
	logout<<"Line# "<<line_count<<": Token <CONST_CHAR> Lexeme "<<Lexeme_To_Char(yytext)<<" found\n";
	// tokenout << "<CONST_CHAR, " << Lexeme_To_Char(yytext) << ">\n";
	TreeNode *tn=new TreeNode(new Symbol_Info(yytext,"CONST_CHAR"),"CONST_CHAR : "+ string(yytext)+"\t<Line : ");
	tn->first_line=tn->last_line=yylineno;
	tn->is_Terminal=true;
	tn->output_text+=(to_string(tn->first_line)+">");
	//yylval.TreeNode=tn;
	//return CONST_CHAR;
	cout<<tn->output_text<<endl;


}
	YY_BREAK
/*operator*/
case 23:
YY_RULE_SETUP
#line 377 "1905028.l"
{
    // Print_token("ADDOP",yytext);
	Print_log(line_count,"ADDOP",yytext);
	TreeNode *tn=new TreeNode(new Symbol_Info(yytext,"ADDOP"),"ADDOP : "+ string(yytext)+"\t<Line : ");
	tn->first_line=tn->last_line=yylineno;
	tn->is_Terminal=true;
	tn->output_text+=(to_string(tn->first_line)+">");
	//yylval.TreeNode=tn;
	//return ADDOP;
	cout<<tn->output_text<<endl;

}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 390 "1905028.l"
{
	// Print_token("MULOP",yytext);
	Print_log(line_count,"MULOP",yytext);
	TreeNode *tn=new TreeNode(new Symbol_Info(yytext,"MULOP"),"MULOP : "+ string(yytext)+"\t<Line : ");
	tn->first_line=tn->last_line=yylineno;
	tn->is_Terminal=true;
	tn->output_text+=(to_string(tn->first_line)+">");
	//yylval.TreeNode=tn;
	//return MULOP;
	cout<<tn->output_text<<endl;

}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 403 "1905028.l"
{
	// Print_token("INCOP",yytext);
	Print_log(line_count,"INCOP",yytext);
	TreeNode *tn=new TreeNode(new Symbol_Info(yytext,"INCOP"),"INCOP : "+ string(yytext)+"\t<Line : ");
	tn->first_line=tn->last_line=yylineno;
	tn->is_Terminal=true;
	tn->output_text+=(to_string(tn->first_line)+">");
	//yylval.TreeNode=tn;
	//return INCOP;
	cout<<tn->output_text<<endl;

}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 416 "1905028.l"
{
	
	Print_log(line_count,"DECOP",yytext);
	TreeNode *tn=new TreeNode(new Symbol_Info(yytext,"DECOP"),"DECOP : "+ string(yytext)+"\t<Line : ");
	tn->first_line=tn->last_line=yylineno;
	tn->is_Terminal=true;
	tn->output_text+=(to_string(tn->first_line)+">");
	//yylval.TreeNode=tn;
	//return DECOP;
	cout<<tn->output_text<<endl;

}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 430 "1905028.l"
{   
	// Print_token("RELOP",yytext);
	Print_log(line_count,"RELOP",yytext);
	TreeNode *tn=new TreeNode(new Symbol_Info(yytext,"RELOP"),"RELOP : "+ string(yytext)+"\t<Line : ");
	tn->first_line=tn->last_line=yylineno;
	tn->is_Terminal=true;
	tn->output_text+=(to_string(tn->first_line)+">");
	//yylval.TreeNode=tn;
	//return RELOP;
	cout<<tn->output_text<<endl;



}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 445 "1905028.l"
{
	// Print_token("BITOP",yytext);
	Print_log(line_count,"BITOP",yytext);
	TreeNode *tn=new TreeNode(new Symbol_Info(yytext,"BITOP"),"BITOP : "+ string(yytext)+"\t<Line : ");
	tn->first_line=tn->last_line=yylineno;
	tn->is_Terminal=true;
	tn->output_text+=(to_string(tn->first_line)+">");
	//yylval.TreeNode=tn;
	//return BITOP;
	cout<<tn->output_text<<endl;

}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 459 "1905028.l"
{
	// Print_token("ASSIGNOP",yytext);
	Print_log(line_count,"ASSIGNOP",yytext);
	TreeNode *tn=new TreeNode(new Symbol_Info(yytext,"ASSIGNOP"),"ASSIGNOP : "+ string(yytext)+"\t<Line : ");
	tn->first_line=tn->last_line=yylineno;
	tn->is_Terminal=true;
	tn->output_text+=(to_string(tn->first_line)+">");
	//yylval.TreeNode=tn;
	//return ASSIGNOP;
	cout<<tn->output_text<<endl;

}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 472 "1905028.l"
{
	// Print_token("LOGICOP",yytext);
	Print_log(line_count,"LOGICOP",yytext);
	TreeNode *tn=new TreeNode(new Symbol_Info(yytext,"LOGICOP"),"LOGICOP : "+ string(yytext)+"\t<Line : ");
	tn->first_line=tn->last_line=yylineno;
	tn->is_Terminal=true;
	tn->output_text+=(to_string(tn->first_line)+">");
	//yylval.TreeNode=tn;
	//return LOGICOP;
	cout<<tn->output_text<<endl;

}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 485 "1905028.l"
{
	// Print_token("NOT",yytext);
	Print_log(line_count,"NOT",yytext);
	TreeNode *tn=new TreeNode(new Symbol_Info(yytext,"NOT"),"NOT : "+ string(yytext)+"\t<Line : ");
	tn->first_line=tn->last_line=yylineno;
	tn->is_Terminal=true;
	tn->output_text+=(to_string(tn->first_line)+">");
	//yylval.TreeNode=tn;
	//return NOT;
	cout<<tn->output_text<<endl;

}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 498 "1905028.l"
{
	// Print_token("LPAREN",yytext);
	Print_log(line_count,"LPAREN",yytext);
	TreeNode *tn=new TreeNode(new Symbol_Info(yytext,"LPAREN"),"LPAREN : "+ string(yytext)+"\t<Line : ");
	tn->first_line=tn->last_line=yylineno;
	tn->is_Terminal=true;
	tn->output_text+=(to_string(tn->first_line)+">");
	//yylval.TreeNode=tn;
	//return LPAREN;
	cout<<tn->output_text<<endl;

}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 511 "1905028.l"
{
	// Print_token("RPAREN",yytext);
	Print_log(line_count,"RPAREN",yytext);
	TreeNode *tn=new TreeNode(new Symbol_Info(yytext,"RAREN"),"RPAREN : "+ string(yytext)+"\t<Line : ");
	tn->first_line=tn->last_line=yylineno;
	tn->is_Terminal=true;
	tn->output_text+=(to_string(tn->first_line)+">");
	//yylval.TreeNode=tn;
	//return RPAREN;
	cout<<tn->output_text<<endl;


}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 525 "1905028.l"
{
	// Print_token("LCURL",yytext);
	Print_log(line_count,"LCURL",yytext);
    // symbolTable.Enter_Scope();
	TreeNode *tn=new TreeNode(new Symbol_Info(yytext,"LCURL"),"LCURL : "+ string(yytext)+"\t<Line : ");
	tn->first_line=tn->last_line=yylineno;
	tn->is_Terminal=true;
	tn->output_text+=(to_string(tn->first_line)+">");
	//yylval.TreeNode=tn;
	//return LCURL;
	cout<<tn->output_text<<endl;

}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 539 "1905028.l"
{
	// Print_token("RCURL",yytext);
	Print_log(line_count,"RCURL",yytext);
    // symbolTable.Exit_Scope();
	TreeNode *tn=new TreeNode(new Symbol_Info(yytext,"RCURL"),"RCURL : "+ string(yytext)+"\t<Line : ");
	tn->first_line=tn->last_line=yylineno;
	tn->is_Terminal=true;
	tn->output_text+=(to_string(tn->first_line)+">");
	//yylval.TreeNode=tn;
	//return RCURL;
	cout<<tn->output_text<<endl;

	
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 554 "1905028.l"
{
	// Print_token("LSQUARE",yytext);
	Print_log(line_count,"LSQUARE",yytext);
	TreeNode *tn=new TreeNode(new Symbol_Info(yytext,"LSQUARE"),"LSQUARE : "+ string(yytext)+"\t<Line : ");
	tn->first_line=tn->last_line=yylineno;
	tn->is_Terminal=true;
	tn->output_text+=(to_string(tn->first_line)+">");
	//yylval.TreeNode=tn;
	//return LSQUARE;
	cout<<tn->output_text<<endl;

}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 566 "1905028.l"
{
	// Print_token("RSQUARE",yytext);
	Print_log(line_count,"RSQUARE",yytext);
	TreeNode *tn=new TreeNode(new Symbol_Info(yytext,"RSQUARE"),"RSQUARE : "+ string(yytext)+"\t<Line : ");
	tn->first_line=tn->last_line=yylineno;
	tn->is_Terminal=true;
	tn->output_text+=(to_string(tn->first_line)+">");
	//yylval.TreeNode=tn;
	//return RSQUARE;
	cout<<tn->output_text<<endl;


}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 580 "1905028.l"
{
	// Print_token("COMMA",yytext);
	Print_log(line_count,"COMMA",yytext);
	TreeNode *tn=new TreeNode(new Symbol_Info(yytext,"COMMA"),"COMMA : "+ string(yytext)+"\t<Line : ");
	tn->first_line=tn->last_line=yylineno;
	tn->is_Terminal=true;
	tn->output_text+=(to_string(tn->first_line)+">");
	//yylval.TreeNode=tn;
	//return COMMA;
	cout<<tn->output_text<<endl;

}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 593 "1905028.l"
{
	// Print_token("SEMICOLON",yytext);
	Print_log(line_count,"SEMICOLON",yytext);
	TreeNode *tn=new TreeNode(new Symbol_Info(yytext,"SEMICOLON"),"SEMICOLON : "+ string(yytext)+"\t<Line : ");
	tn->first_line=tn->last_line=yylineno;
	tn->is_Terminal=true;
	tn->output_text+=(to_string(tn->first_line)+">");
	//yylval.TreeNode=tn;
	//return SEMICOLON;
	cout<<tn->output_text<<endl;

}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 606 "1905028.l"
{
	lexeme_start_line=line_count;
	current_lexeme=yytext;
	// cout<<"Comment Start\n";
	BEGIN SINGLE_LINE_COMMENT_STATE;
	
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 614 "1905028.l"
{
	current_lexeme+=yytext;
}
	YY_BREAK
case 42:
/* rule 42 can match eol */
YY_RULE_SETUP
#line 618 "1905028.l"
{
	current_lexeme+=yytext;line_count++;
	// cout<<"new line in comment\n";
}
	YY_BREAK
case 43:
/* rule 43 can match eol */
YY_RULE_SETUP
#line 623 "1905028.l"
{
	line_count++;
	// cout<<"Comment End\n";
	Print_log(lexeme_start_line,"SINGLE LINE COMMENT",current_lexeme);
	BEGIN INITIAL;
}
	YY_BREAK
case YY_STATE_EOF(SINGLE_LINE_COMMENT_STATE):
#line 630 "1905028.l"
{
	line_count++;
	// cout<<"Comment End\n";
	Print_log(lexeme_start_line,"SINGLE LINE COMMENT",current_lexeme);
	// symbolTable.PrintAllScope();
	// logout<<"Total lines: "<<line_count<<"\n";
	// logout<<"Total errors: "<<errors<<"\n";
	return 0;
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 640 "1905028.l"
{
	current_lexeme=yytext;
	lexeme_start_line=line_count;
	BEGIN MULTILINE_COMMENT_STATE;
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 646 "1905028.l"
{
	current_lexeme+=yytext;
}
	YY_BREAK
case 46:
/* rule 46 can match eol */
YY_RULE_SETUP
#line 649 "1905028.l"
{
	line_count++;current_lexeme+=yytext;
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 653 "1905028.l"
{
	current_lexeme+=yytext;
	Print_log(lexeme_start_line,"MULTI LINE COMMENT",current_lexeme);
	BEGIN INITIAL;
}
	YY_BREAK
case YY_STATE_EOF(MULTILINE_COMMENT_STATE):
#line 659 "1905028.l"
{
	Print_error(line_count,current_lexeme,"UNFINISHED_COMMENT");
	errors++;
	// line_count--;
	// symbolTable.PrintAllScope();
	// logout<<"Total lines: "<<line_count<<"\n";
	// logout<<"Total errors: "<<errors<<"\n";
	return 0;
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 670 "1905028.l"
{
	str_token="";
	single_line_string=true;
	current_lexeme=yytext;
	lexeme_start_line=line_count;
	BEGIN STRING_STATE;
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 678 "1905028.l"
{
	current_lexeme+=yytext;
	if(single_line_string){
		Print_log(lexeme_start_line,"SINGLE LINE STRING",current_lexeme);
		// Print_token("SINGLE LINE STRING",str_token);
	}
	else{
		Print_log(lexeme_start_line,"MULTI LINE STRING",current_lexeme);
		// Print_token("MULTI LINE STRING",str_token);
	}
	
	BEGIN INITIAL;
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 692 "1905028.l"
{
	current_lexeme+=yytext;
	str_token+="\"";
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 697 "1905028.l"
{
	// cout<<"Found escape char\n";
	str_token+=ESC_IN_STRING(yytext);
	current_lexeme+=yytext;
}
	YY_BREAK
case 52:
/* rule 52 can match eol */
YY_RULE_SETUP
#line 703 "1905028.l"
{
	current_lexeme+=yytext;
	line_count++;
	single_line_string=false;
}
	YY_BREAK
case 53:
/* rule 53 can match eol */
YY_RULE_SETUP
#line 709 "1905028.l"
{
	errors++;
	Print_error(line_count++,current_lexeme,"UNFINISHED_STRING");
	BEGIN INITIAL;
}
	YY_BREAK
case YY_STATE_EOF(STRING_STATE):
#line 715 "1905028.l"
{
	line_count--;errors++;
	Print_error(line_count,current_lexeme,"UNFINISHED_STRING");
	// symbolTable.PrintAllScope();
	logout<<"Total lines: "<<line_count<<"\n";
	logout<<"Total errors: "<<errors<<"\n";
	return 0;
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 724 "1905028.l"
{
	current_lexeme+=yytext;
	str_token+=yytext;
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 729 "1905028.l"
{
	Print_error(line_count,yytext,"TOO_MANY_DECIMAL_POINTS");
	errors++;
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 734 "1905028.l"
{
	Print_error(line_count,yytext,"ILLFORMED_NUMBER");
	errors++;
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 739 "1905028.l"
{
	Print_error(line_count,yytext,"MULTICHAR_CONST_CHAR");
	errors++;
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 744 "1905028.l"
{
	Print_error(line_count,yytext,"INVALID_ID_SUFFIX_NUM_PREFIX");
	errors++;
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 749 "1905028.l"
{
	Print_error(line_count,yytext,"EMPTY_CONST_CHAR");
	errors++;
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 754 "1905028.l"
{
	Print_error(line_count,yytext,"UNFINISHED_CONST_CHAR");
	errors++;
}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 761 "1905028.l"
{
	// symbolTable.PrintAllScope();
	logout<<"Total lines: "<<line_count<<"\n";
	logout<<"Total errors: "<<errors<<"\n";
	return 0;
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 769 "1905028.l"
{
	Print_error(line_count,yytext,"UNRECOGNIZED_CHAR");
	errors++;
}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 782 "1905028.l"
ECHO;
	YY_BREAK
#line 1876 "wordcount.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 203 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 203 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 202);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 782 "1905028.l"


int main(int argc, char** argv) {
	if(argc!=2){
		printf("Please provide input file name and try again\n");
		return 0;
	}
	
	FILE *fin=fopen(argv[1],"r");
	if(fin==NULL){
		printf("Cannot open specified file\n");
		return 0;
	}
	
	// tokenout.open("1905028_token.txt");
	logout.open("1905028_log.txt");
	freopen("rough1.txt","w",stdout);



	// freopen("1905028_log.txt","w",stdout);

	yyin= fin;
	yylex();
	fclose(yyin);
	
	return 0;
}

